### ISSUE TITLE
There is one more annoying unopened tag

### ISSUE THREAD

**Issue by KosmX** [zabbly/incus-ui-canonical#13]
like #12 but 12 lines below that.

exactly there: 
https://github.com/zabbly/incus-ui-canonical/blob/936bc19bc253e018bc160b640856e801963d6489/src/pages/login/CertificateAdd.tsx#L43C1-L43C17

**Comment by KosmX** [comment]
I removed that locally and it builds without that, so probably this is the last one.

**Comment by stgraber** [comment]
Yep, just noticed it too in a failed build, that's what I get for doing fixes on a system that's not setup to build this tree...

Anyway, should be fixed now.
