### ISSUE TITLE
Exception accessing vm in UI

### ISSUE THREAD

**Issue by madeiba** [zabbly/incus-ui-canonical#23]
# Description

Trying to access to several VMs in Incus-UI I receive this exception. 
There is an VM I can access without problem. I think I build this vm with the previous version of incus (6.7) but I'm not sure.
I've tryed with firefox and chromium browsers.

# Metadata

UI Version: 0.14
Path: /ui/project/default/instance/deb1

# Stacktrace

```
r@https://localhost:2443/ui/assets/InstanceDetail-BfDPbcS9.js:1:6156
Ya/_<@https://localhost:2443/ui/assets/InstanceDetail-BfDPbcS9.js:1:6186
Ya@https://localhost:2443/ui/assets/InstanceDetail-BfDPbcS9.js:1:6209
K_@https://localhost:2443/ui/assets/index-BWo7GFyQ.js:39:17000
yg@https://localhost:2443/ui/assets/index-BWo7GFyQ.js:41:3139
jj@https://localhost:2443/ui/assets/index-BWo7GFyQ.js:41:44804
Pj@https://localhost:2443/ui/assets/index-BWo7GFyQ.js:41:39768
JM@https://localhost:2443/ui/assets/index-BWo7GFyQ.js:41:39696
vf@https://localhost:2443/ui/assets/index-BWo7GFyQ.js:41:39547
xg@https://localhost:2443/ui/assets/index-BWo7GFyQ.js:41:35914
nS@https://localhost:2443/ui/assets/index-BWo7GFyQ.js:41:36717
qo@https://localhost:2443/ui/assets/index-BWo7GFyQ.js:39:3274
Zn/<@https://localhost:2443/ui/assets/index-BWo7GFyQ.js:41:34246

```

**Comment by stgraber** [comment]
Hmm, this stacktrace really isn't helpful at all...
Does the web browser show you anything more useful when accessing the page?

**Comment by presztak** [comment]
@stgraber the stack trace looks exactly the same as the one in https://github.com/zabbly/incus-ui-canonical/issues/15, so it has already been fixed.
