### ISSUE TITLE
missing login instructions, get JSON instead

### ISSUE THREAD

**Issue by divinity76** [zabbly/incus-ui-canonical#25]
Ubuntu24.04 AMD64, Following the "Setting up the UI" instructions, I basically did
```
sh -c 'cat <<EOF > /etc/apt/sources.list.d/zabbly-incus-stable.sources
Enabled: yes
Types: deb
URIs: https://pkgs.zabbly.com/incus/stable
Suites: $(. /etc/os-release && echo ${VERSION_CODENAME})
Components: main
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/zabbly.asc

EOF';
apt update;
apt full-upgrade;
apt-get install incus incus-ui-canonical;
incus admin init; (using mostly just the default settings, no cluster)
incus config set core.https_address :8443;
```
and pointed my browser to https://localhost:8443 , after accepting the certificate, I just get this JSON:
```
{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":["/1.0"]}
```
and if I try to enter https://localhost:8443/ui/login I get
```
{"type":"error","status":"","status_code":0,"operation":"","error_code":404,"error":"not found","metadata":null}
```
![image](https://github.com/user-attachments/assets/9744572f-cf7a-45a7-8580-f205103f6911)

Please advice

**Comment by divinity76** [comment]
may be related to https://github.com/canonical/lxd/issues/12997

**Comment by divinity76** [comment]
maybe https://github.com/zabbly/incus-ui-canonical/blob/a608020b7f6d1925fb402b36a2a5960f3caa5b25/src/pages/login/Login.tsx#L16

is stuck on true for some reason?

**Comment by stgraber** [comment]
What does `https://localhost:8443/ui/` show?

**Comment by stgraber** [comment]
Also what do you get when you do `incus webui`?

**Comment by divinity76** [comment]
omg, i somehow didn't have `incus-ui-canonical` installed. I'm so sorry.

Could've sworn I had installed it already. just installing it seems to have fixed everything. closing.

fwiw

https://localhost:8443/ui/ gives:
```
{"type":"error","status":"","status_code":0,"operation":"","error_code":404,"error":"not found","metadata":null}
```
and
```
$ incus webui
Error: The server doesn't have a web UI installed
```
