### ISSUE TITLE
Consider updating README.md to remove LXD and Canonical references

### ISSUE THREAD

**Issue by RadxaYuntian** [zabbly/incus-ui-canonical#7]
Glad to see this finally get its own repository. Hopefully this means we can more easily add Incus specific features in the future.

README still reads as LXD-UI though.

**Comment by stgraber** [comment]
This repo is just an here to build up a set of minimal patches, it's not meant as standalone fork of the LXD UI codebase.

Changing the README would just increase the likelihood of conflicts when we rebase onto a new version of LXD UI so it's not really worth it. Also worth noting that we will not keep a linear history on this repo, it will actively get rebased on the LXD UI repo.
